# Generated by Django 5.1.2 on 2024-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50, verbose_name="Name")),
                ("email", models.CharField(max_length=50, verbose_name="Name")),
                ("phone", models.CharField(max_length=50, verbose_name="Name")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("is_read", models.BooleanField(verbose_name="Is Read?")),
            ],
        ),
    ]
