# Generated by Django 5.1.2 on 2024-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Is Read?"),
        ),
    ]
