# Generated by Django 5.1.2 on 2024-10-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriweb", "0002_alter_contact_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
        ),
    ]
