# Generated by Django 5.1.2 on 2024-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriweb", "0003_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="sender",
            field=models.CharField(
                blank=True,
                choices=[("Farmer", "Farmer"), ("Business", "Business")],
                max_length=10,
                null=True,
                verbose_name="Sender",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="Phone"),
        ),
    ]
